# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8256daceb1881ccd3cc6323c96caa09f3823c0ea57c354ab0d5b57d9b2df5858977907454ae00a2ce559f3fc396a0542d96c43a7b79d8b150634fb4212f1069
  stripe_api_key: replace_me
  stripe_publishable_key: replace_me

test:
  secret_key_base: cdcc3a567d9b103d3a217a9a9544a50bd54de98e76ecc2e0906872eff228dc8de229000e2335b08af9d9416c762c00d71310b243c6dc053f7a522c51943b04fd
  stripe_api_key: replace_me
  stripe_publishable_key: replace_me

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
